import { DuaItem } from '../types';

export const AUTHENTIC_DUAS: DuaItem[] = [
  // --- SALAT TIME & PRAYER DUAS ---
  {
    id: 'post_salah_tasbeeh',
    title: 'Tasbeeh After Fard Salah (Sunnah 33-33-33-1)',
    category: 'salat',
    timing: 'Immediately after concluding obligatory prayer',
    arabic: 'سُبْحَانَ ٱللَّٰهِ (٣٣) • ٱلْحَمْدُ لِلَّٰهِ (٣٣) • ٱللَّٰهُ أَكْبَرُ (٣٣) • لَا إِلَٰهَ إِلَّا ٱللَّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ ٱلْمُلْكُ وَلَهُ ٱلْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'Subḥān Allāh (33x), Al-ḥamdu lillāh (33x), Allāhu Akbar (33x), Lā ilāha illallāhu waḥdahu lā sharīka lahu...',
    translation: 'Glory be to Allah (33 times), Praise be to Allah (33 times), Allah is the Greatest (33 times), followed by: "There is no true deity except Allah alone, without partner; to Him belongs all sovereignty and praise, and He has power over all things."',
    reference: 'Sahih Muslim 597',
    virtue: 'Whoever recites this after every prescribed prayer will have his sins forgiven even if they are like the foam of the sea.',
    suggestedCount: 100,
  },
  {
    id: 'post_salah_ayatul_kursi',
    title: 'Ayat al-Kursi After Every Obligatory Prayer',
    category: 'salat',
    timing: 'After every Fard prayer',
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    transliteration: 'Allāhu lā ilāha illā huwal-ḥayyul-qayyūm, lā ta\'khudhuhū sinatuw-wa lā nawm, lahū mā fis-samāwāti wa mā fil-arḍ...',
    translation: 'Allah! There is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth...',
    reference: 'Surah Al-Baqarah (2:255) / Sunan an-Nasa\'i (Al-Kubra 9848)',
    virtue: 'The Messenger of Allah ﷺ said: "Whoever recites Ayat al-Kursi immediately after each prescribed prayer, there will be nothing between him and his entering Paradise except death."',
    suggestedCount: 1,
  },
  {
    id: 'post_salah_istighfar',
    title: 'Istighfar & Peace Invocation After Tasleem',
    category: 'salat',
    timing: 'Immediately upon completing Salah',
    arabic: 'أَسْتَغْفِرُ ٱللَّٰهَ (٣) • اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ',
    transliteration: 'Astaghfirullāh (3x), Allāhumma antas-salām wa minkas-salām, tabārakta yā dhal-jalāli wal-ikrām.',
    translation: 'I seek forgiveness from Allah (3 times). O Allah, You are Peace and from You comes peace. Blessed are You, O Owner of majesty and honor.',
    reference: 'Sahih Muslim 591',
    virtue: 'Sunnah uttered by the Prophet ﷺ immediately upon turning from prayer.',
    suggestedCount: 3,
  },
  {
    id: 'after_adhan_dua',
    title: 'Dua After Hearing the Call to Prayer (Adhan)',
    category: 'salat',
    timing: 'After the Adhan concludes and sending Salawat',
    arabic: 'اللَّهُمَّ رَبَّ هَٰذِهِ الدَّعْوَةِ التَّامَّةِ، وَالصَّلَاةِ الْقَائِمَةِ، آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ، وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ',
    transliteration: 'Allāhumma Rabba hādhihid-da\'watit-tāmmah, waṣ-ṣalātil-qā\'imah, āti Muḥammadanil-wasīlata wal-faḍīlah, wab\'ath-hu maqāmam-maḥmūdanil-ladhī wa\'adtah.',
    translation: 'O Allah, Owner of this perfect call and established prayer, grant Muhammad the Wasilah (highest station in Paradise) and virtue, and resurrect him to the praised station which You have promised him.',
    reference: 'Sahih al-Bukhari 614',
    virtue: 'Intercession of the Prophet ﷺ will become permissible for the reciter on the Day of Judgment.',
    suggestedCount: 1,
  },
  {
    id: 'dua_entering_masjid',
    title: 'Dua for Entering the Mosque',
    category: 'salat',
    timing: 'Stepping into the mosque with right foot',
    arabic: 'بِسْمِ اللَّهِ، وَالصَّلَاةُ وَالسَّلَامُ عَلَىٰ رَسُولِ اللَّهِ، اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    transliteration: 'Bismillāh, waṣ-ṣalātu was-salāmu \'alā Rasūlillāh, Allāhummaf-taḥ lī abwāba raḥmatik.',
    translation: 'In the name of Allah, and peace and blessings upon the Messenger of Allah. O Allah, open for me the gates of Your mercy.',
    reference: 'Sahih Muslim 713, Abu Dawud 465',
    virtue: 'Invokes Divine mercy as you enter the house of Allah.',
    suggestedCount: 1,
  },
  {
    id: 'dua_steadfastness_prayer',
    title: 'Dua of Ibrahim for Steadfastness in Salah',
    category: 'salat',
    timing: 'In Sujood, Tashahhud, or anytime',
    arabic: 'رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي ۚ رَبَّنَا وَتَقَبَّلْ دُعَاءِ',
    transliteration: 'Rabbi-j\'alnī muqīmaṣ-ṣalāti wa min dhurriyyatī, Rabbanā wa taqabbal du\'ā\'.',
    translation: 'My Lord, make me an establisher of prayer, and [many] from my descendants. Our Lord, and accept my supplication.',
    reference: 'Surah Ibrahim (14:40)',
    virtue: 'The sacred prayer of Prophet Ibrahim (Abraham) AS for lifelong devotion to Salah for oneself and lineage.',
    suggestedCount: 3,
  },

  // --- QURANIC DUAS (RABBANA & PROPHETIC DUAS) ---
  {
    id: 'quran_rabbana_dunya_akhirah',
    title: 'Rabbana Atina fid-Dunya Hasanatan',
    category: 'quran',
    timing: 'During Tawaf, after prayers, and in daily remembrance',
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    transliteration: 'Rabbanā ātinā fid-dunyā ḥasanatan wa fil-ākhirati ḥasanatan wa qinā \'adhāban-nār.',
    translation: 'Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.',
    reference: 'Surah Al-Baqarah (2:201)',
    virtue: 'The most frequent supplication of the Prophet Muhammad ﷺ (Sahih al-Bukhari 6389).',
    suggestedCount: 10,
  },
  {
    id: 'quran_yunus_dua',
    title: 'Ayat Karima — Dua of Prophet Yunus (Jonah)',
    category: 'quran',
    timing: 'During distress, anxiety, difficulties, or need',
    arabic: 'لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ',
    transliteration: 'Lā ilāha illā Anta subḥānaka innī kuntu minaẓ-ẓālimīn.',
    translation: 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.',
    reference: 'Surah Al-Anbiya (21:87)',
    virtue: 'Prophet Muhammad ﷺ said: "No Muslim supplicates with this in any difficulty except that Allah answers his call." (Jami` at-Tirmidhi 3505).',
    suggestedCount: 40,
  },
  {
    id: 'quran_musa_speech_anxiety',
    title: 'Dua of Prophet Musa for Confidence & Clarity',
    category: 'quran',
    timing: 'Before speaking, exams, interviews, or difficult tasks',
    arabic: 'رَبِّ اشْرَحْ لِي صَدْرِي • وَيَسِّرْ لِي أَمْرِي • وَاحْلُلْ عُقْدَةً مِّن لِّسَانِي • يَفْقَهُوا قَوْلِي',
    transliteration: 'Rabbish-raḥ lī ṣadrī, wa yassir lī amrī, waḥ-lul \'uqdatam-mil-lisānī, yafqahū qawlī.',
    translation: 'My Lord, expand for me my breast [with assurance], and ease for me my task, and untie the knot from my tongue, that they may understand my speech.',
    reference: 'Surah Ta-Ha (20:25-28)',
    virtue: 'Removes hesitation, relieves anxiety, and grants eloquence and ease.',
    suggestedCount: 7,
  },
  {
    id: 'quran_firm_heart',
    title: 'Supplication for Steadfastness of Heart',
    category: 'quran',
    timing: 'Daily spiritual preservation',
    arabic: 'رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً ۚ إِنَّكَ أَنتَ الْوَهَّابُ',
    transliteration: 'Rabbanā lā tuzigh qulūbanā ba\'da idh hadaytanā wa hab lanā mil-ladunka raḥmah, innaka Antal-Wahhāb.',
    translation: 'Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.',
    reference: 'Surah Ali \'Imran (3:8)',
    virtue: 'Guards faith and shields the believer from wavering or doubts.',
    suggestedCount: 3,
  },
  {
    id: 'quran_parents_mercy',
    title: 'Dua for Parents',
    category: 'quran',
    timing: 'Daily remembrance for parents (living or deceased)',
    arabic: 'رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    transliteration: 'Rabbir-ḥam-humā kamā rabbayānī ṣaghīrā.',
    translation: 'My Lord, have mercy upon them as they brought me up [when I was] small.',
    reference: 'Surah Al-Isra (17:24)',
    virtue: 'Fulfills the Divine commandment of dutifulness and gratitude to parents.',
    suggestedCount: 10,
  },
  {
    id: 'quran_increase_knowledge',
    title: 'Dua for Knowledge & Wisdom',
    category: 'quran',
    timing: 'When studying, reading Quran, or seeking wisdom',
    arabic: 'رَّبِّ زِدْنِي عِلْمًا',
    transliteration: 'Rabbi zidnī \'ilmā.',
    translation: 'My Lord, increase me in knowledge.',
    reference: 'Surah Ta-Ha (20:114)',
    virtue: 'The only thing Allah commanded the Prophet ﷺ to ask for an increase in.',
    suggestedCount: 7,
  },
  {
    id: 'quran_adam_forgiveness',
    title: 'Dua of Adam & Hawwa for Forgiveness',
    category: 'quran',
    timing: 'Seeking repentance (Tawbah)',
    arabic: 'رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ',
    transliteration: 'Rabbanā ẓalamnā anfusanā wa il-lam taghfir lanā wa tarḥamnā lanakūnanna minal-khāsirīn.',
    translation: 'Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.',
    reference: 'Surah Al-A\'raf (7:23)',
    virtue: 'The heartfelt repentance that resulted in forgiveness for mankind\'s first parents.',
    suggestedCount: 3,
  },

  // --- PROPHETIC HADITH & VIRTUES OF ZIKR ---
  {
    id: 'hadith_sayyidul_istighfar',
    title: 'Sayyidul Istighfar — Master of Forgiveness',
    category: 'hadith',
    timing: 'Recited once in the morning and once in the evening',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: 'Allāhumma Anta Rabbī lā ilāha illā Ant, khalaqtanī wa anā \'abduk, wa anā \'alā \'ahdika wa wa\'dika mas-taṭa\'t, a\'ūdhu bika min sharri mā ṣana\'t, abū\'u laka bi-ni\'matika \'alayya, wa abū\'u bi-dhambī faghfir lī fa-innahū lā yaghfirudh-dhunūba illā Ant.',
    translation: 'O Allah, You are my Lord; none has the right to be worshipped but You. You created me and I am Your slave, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favors upon me, and I acknowledge my sin, so forgive me, for none forgives sins except You.',
    reference: 'Sahih al-Bukhari 6306',
    virtue: 'The Prophet ﷺ said: "Whoever says this during the day with firm belief in it and dies before evening will be among the people of Paradise; and whoever says it at night and dies before morning will be among the people of Paradise."',
    suggestedCount: 1,
  },
  {
    id: 'hadith_kalimatani_habibatani',
    title: 'Two Words Beloved to the Most Merciful',
    category: 'hadith',
    timing: 'Anytime throughout the day',
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ',
    transliteration: 'Subḥānallāhi wa bi-ḥamdih, Subḥānallāhil-\'Aẓīm.',
    translation: 'Glory be to Allah and His is the praise, Glory be to Allah the Supreme.',
    reference: 'Sahih al-Bukhari 6406, Sahih Muslim 2694',
    virtue: 'Prophet Muhammad ﷺ said: "Two words are light on the tongue, heavy in the Balance, and beloved to the Most Merciful."',
    suggestedCount: 100,
  },
  {
    id: 'hadith_salawat',
    title: 'Sending Blessings upon the Prophet ﷺ (Salawat)',
    category: 'hadith',
    timing: 'Especially on Fridays, and throughout daily routine',
    arabic: 'اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ',
    transliteration: 'Allāhumma ṣalli \'alā Muḥammadin wa \'alā āli Muḥammad, kamā ṣallayta \'alā Ibrāhīma wa \'alā āli Ibrāhīm, innaka Ḥamīdum-Majīd.',
    translation: 'O Allah, bestow Your blessings upon Muhammad and the family of Muhammad, as You bestowed blessings upon Ibrahim and the family of Ibrahim. Indeed, You are Praiseworthy and Glorious.',
    reference: 'Sahih al-Bukhari 3370',
    virtue: 'The Messenger of Allah ﷺ said: "Whoever sends blessings upon me once, Allah will send blessings upon him tenfold and erase ten sins." (Sahih Muslim 408).',
    suggestedCount: 100,
  },
  {
    id: 'hadith_subhanallahi_wa_bihamdihi_100',
    title: 'SubhanAllahi wa biHamdihi (100 times)',
    category: 'hadith',
    timing: 'Morning and evening',
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    transliteration: 'Subḥānallāhi wa bi-ḥamdih.',
    translation: 'Glory be to Allah and praise be to Him.',
    reference: 'Sahih al-Bukhari 6405',
    virtue: 'The Prophet ﷺ said: "Whoever says: \'Glory be to Allah and His is the praise\' 100 times a day, his sins will be forgiven even if they are like the foam of the sea."',
    suggestedCount: 100,
  },
  {
    id: 'hadith_la_hawla',
    title: 'A Treasure from Beneath the Throne',
    category: 'hadith',
    timing: 'In times of weakness, stress, or worship',
    arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِٱللَّٰهِ ٱلْعَلِيِّ ٱلْعَظِيمِ',
    transliteration: 'Lā ḥawla wa lā quwwata illā billāhil-\'Aliyyil-\'Aẓīm.',
    translation: 'There is no power and no strength except with Allah, the Most High, the Supreme.',
    reference: 'Sahih al-Bukhari 6384, Sahih Muslim 2704',
    virtue: 'Prophet Muhammad ﷺ described it as "a treasure from the treasures of Paradise".',
    suggestedCount: 33,
  },

  // --- MORNING & EVENING REMEMBRANCE ---
  {
    id: 'adhkar_radheetu_billah',
    title: 'Contentment with Allah, Islam, and the Prophet ﷺ',
    category: 'morning_evening',
    timing: 'Morning and evening (3 times)',
    arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا',
    transliteration: 'Raḍītu billāhi Rabban, wa bil-Islāmi dīnan, wa bi-Muḥammadin ṣallallāhu \'alayhi wa sallama nabiyyā.',
    translation: 'I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad (peace and blessings of Allah be upon him) as my Prophet.',
    reference: 'Sunan Abi Dawud 5072, Jami` at-Tirmidhi 3389',
    virtue: '"It is a right upon Allah that He will surely make him pleased on the Day of Resurrection."',
    suggestedCount: 3,
  },
  {
    id: 'adhkar_bismillahilladhi',
    title: 'Shield from All Harm in Heavens and Earth',
    category: 'morning_evening',
    timing: 'Morning and evening (3 times)',
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    transliteration: 'Bismillāhil-ladhī lā yaḍurru ma\'as-mihī shay\'un fil-arḍi wa lā fis-samā\'i wa Huwas-Samī\'ul-\'Alīm.',
    translation: 'In the name of Allah with whose Name nothing can cause harm in the earth or in the heavens, and He is the All-Hearing, the All-Knowing.',
    reference: 'Sunan Abi Dawud 5088, Jami` at-Tirmidhi 3388',
    virtue: 'Recited 3 times in morning and evening: "Nothing shall harm him."',
    suggestedCount: 3,
  },
  {
    id: 'adhkar_ya_hayyu_ya_qayyoom',
    title: 'Invocation of the Ever-Living, Sustainer of All',
    category: 'morning_evening',
    timing: 'Morning and evening, or in moments of anxiety',
    arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلَا تَكِلْنِي إِلَىٰ نَفْسِي طَرْفَةَ عَيْنٍ',
    transliteration: 'Yā Ḥayyu yā Qayyūm, bi-raḥmatika astaghīth, aṣliḥ lī sha\'nī kullah, wa lā takilnī ilā nafsī ṭarfata \'ayn.',
    translation: 'O Ever-Living, O Sustainer of all existence, by Your mercy I seek assistance. Rectify for me all of my affairs and do not leave me to myself even for the blink of an eye.',
    reference: 'Mustadrak al-Hakim 1/545, Sunan an-Nasa\'i (Al-Kubra 10405)',
    virtue: 'Sunnah advice taught by the Prophet ﷺ to his daughter Fatima (RA).',
    suggestedCount: 3,
  },
  {
    id: 'adhkar_hasbiyallah_7',
    title: 'HasbiyAllahu La Ilaha Illa Huwa (7 times)',
    category: 'morning_evening',
    timing: 'Morning and evening (7 times)',
    arabic: 'حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ ۖ عَلَيْهِ تَوَكَّلْتُ ۖ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
    transliteration: 'Ḥasbiyallāhu lā ilāha illā Hū, \'alayhi tawakkaltu wa Huwa Rabbul-\'Arshil-\'Aẓīm.',
    translation: 'Sufficient for me is Allah; there is no deity except Him. Upon Him I have relied, and He is the Lord of the Great Throne.',
    reference: 'Surah At-Tawbah (9:129) / Sunan Abi Dawud 5081',
    virtue: '"Whoever says it seven times in the morning and evening, Allah will suffice him for whatever concerns him of the affairs of this world and the Hereafter."',
    suggestedCount: 7,
  }
];
