import { HadithItem } from '../types';

export const AUTHENTIC_HADITHS: HadithItem[] = [
  {
    id: 'bukhari_1',
    book: 'Sahih al-Bukhari',
    hadithNumber: '1',
    chapter: 'Revelation & Intentions',
    narrator: 'Umar ibn al-Khattab (RA)',
    arabicText: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى، فَمَنْ كَانَتْ هِجْرَتُهُ إِلَى دُنْيَا يُصِيبُهَا أَوْ إِلَى امْرَأَةٍ يَنْكِحُهَا، فَهِجْرَتُهُ إِلَى مَا هَاجَرَ إِلَيْهِ.',
    englishTranslation: 'The rewards of deeds depend upon the intentions and every person will get the reward according to what he has intended. So whoever emigrated for worldly benefits or for a woman to marry, his emigration was for what he emigrated for.',
    topic: 'Faith & Tawheed',
    grade: 'Sahih',
    reflection: 'The foundation of all actions in Islam begins in the heart. A pure intention transforms simple daily routines into acts of worship.',
  },
  {
    id: 'muslim_2564',
    book: 'Sahih Muslim',
    hadithNumber: '2564',
    chapter: 'Virtue, Good Manners and Joining Ties',
    narrator: 'Abu Hurairah (RA)',
    arabicText: 'إِنَّ اللَّهَ لاَ يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ.',
    englishTranslation: 'Verily Allah does not look at your outward appearances or your wealth, but rather He looks at your hearts and your deeds.',
    topic: 'Character & Akhlaq',
    grade: 'Sahih',
    reflection: 'Inner spiritual purity and righteous behavior outweigh any superficial worldly status or cosmetic appearance.',
  },
  {
    id: 'bukhari_6407',
    book: 'Sahih al-Bukhari',
    hadithNumber: '6407',
    chapter: 'Remembrance of Allah (Dhikr)',
    narrator: 'Abu Musa al-Ash\'ari (RA)',
    arabicText: 'مَثَلُ الَّذِي يَذْكُرُ رَبَّهُ وَالَّذِي لاَ يَذْكُرُ رَبَّهُ مَثَلُ الْحَىِّ وَالْمَيِّتِ.',
    englishTranslation: 'The example of the one who remembers his Lord in comparison to the one who does not remember his Lord is like that of the living and the dead.',
    topic: 'Dhikr & Dua',
    grade: 'Sahih',
    reflection: 'Dhikr is the life-breath of the soul. Without constant remembrance of Allah, the heart withers into spiritual lifelessness.',
  },
  {
    id: 'bukhari_6405',
    book: 'Sahih al-Bukhari',
    hadithNumber: '6405',
    chapter: 'Virtues of Tasbeeh & Tahmeed',
    narrator: 'Abu Hurairah (RA)',
    arabicText: 'كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَانِ، ثَقِيلَتَانِ فِي الْمِيزَانِ، حَبِيبَتَانِ إِلَى الرَّحْمَنِ: سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ.',
    englishTranslation: 'Two phrases are light on the tongue, heavy on the scales of judgment, and deeply beloved to the Most Merciful: SubhanAllahi wa bihamdihi, SubhanAllahil-Azeem (Glory be to Allah and His is the praise, Glory be to Allah the Almighty).',
    topic: 'Dhikr & Dua',
    grade: 'Sahih',
    reflection: 'Tremendous divine reward for very brief, consistent invocations throughout the busy hours of your day.',
  },
  {
    id: 'muslim_223',
    book: 'Sahih Muslim',
    hadithNumber: '223',
    chapter: 'The Book of Purification',
    narrator: 'Abu Malik al-Ash\'ari (RA)',
    arabicText: 'الطُّهُورُ شَطْرُ الإِيمَانِ، وَالْحَمْدُ لِلَّهِ تَمْلأُ الْمِيزَانَ، وَسُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ تَمْلآنِ - أَوْ تَمْلأُ - مَا بَيْنَ السَّمَاوَاتِ وَالأَرْضِ، وَالصَّلاَةُ نُورٌ، وَالصَّدَقَةُ بُرْهَانٌ، وَالصَّبْرُ ضِيَاءٌ، وَالْقُرْآنُ حُجَّةٌ لَكَ أَوْ عَلَيْكَ.',
    englishTranslation: 'Purification is half of faith. Al-hamdu lillah (Praise be to Allah) fills the scale. SubhanAllah and Al-hamdu lillah fill what is between the heavens and the earth. Prayer is a radiant light, charity is proof of faith, patience is an illuminating brightness, and the Quran is an argument for you or against you.',
    topic: 'Salah & Purification',
    grade: 'Sahih',
    reflection: 'Comprehensive blueprint for the Muslim believer connecting physical purity, prayer, charity, perseverance, and Quranic devotion.',
  },
  {
    id: 'tirmidhi_2003',
    book: 'Jami` at-Tirmidhi',
    hadithNumber: '2003',
    chapter: 'Righteousness and Kindness',
    narrator: 'Abu Hurairah (RA)',
    arabicText: 'أَكْمَلُ الْمُؤْمِنِينَ إِيمَانًا أَحْسَنُهُمْ خُلُقًا، وَخِيَارُكُمْ خِيَارُكُمْ لِنِسَائِهِمْ.',
    englishTranslation: 'The most complete of believers in faith is the one with the best character, and the best of you are those who are best to their wives and families.',
    topic: 'Character & Akhlaq',
    grade: 'Sahih',
    reflection: 'The truest test of religious character is not outward ritualism, but how gentleness, empathy, and honor are displayed inside one\'s home.',
  },
  {
    id: 'bukhari_6011',
    book: 'Sahih al-Bukhari',
    hadithNumber: '6011',
    chapter: 'Good Manners & Mercy',
    narrator: 'An-Nu\'man ibn Bashir (RA)',
    arabicText: 'مَثَلُ الْمُؤْمِنِينَ فِي تَوَادِّهِمْ وَتَرَاحُمِهِمْ وَتَعَاطُفِهِمْ مَثَلُ الْجَسَدِ إِذَا اشْتَكَى مِنْهُ عُضْوٌ تَدَاعَى لَهُ سَائِرُ الْجَسَدِ بِالسَّهَرِ وَالْحُمَّى.',
    englishTranslation: 'The likeness of the believers in their mutual love, mercy, and compassion is that of a single body; when any limb suffers, the entire body responds to it with wakefulness and fever.',
    topic: 'Charity & Kindness',
    grade: 'Sahih',
    reflection: 'Cultivating universal empathy and solidarity with suffering human beings and fellow believers worldwide.',
  },
  {
    id: 'muslim_2699',
    book: 'Sahih Muslim',
    hadithNumber: '2699',
    chapter: 'Seeking Knowledge & Gathering for Dhikr',
    narrator: 'Abu Hurairah (RA)',
    arabicText: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ، وَمَا اجْتَمَعَ قَوْمٌ فِي بَيْتٍ مِنْ بُيُوتِ اللَّهِ يَتْلُونَ كِتَابَ اللَّهِ وَيَتَدَارَسُونَهُ بَيْنَهُمْ إِلاَّ نَزَلَتْ عَلَيْهِمُ السَّكِينَةُ، وَغَشِيَتْهُمُ الرَّحْمَةُ وَحَفَّتْهُمُ الْمَلاَئِكَةُ، وَذَكَرَهُمُ اللَّهُ فِيمَنْ عِنْدَهُ.',
    englishTranslation: 'Whoever travels a path seeking knowledge, Allah will make easy for him a path to Paradise. No people gather together in one of the houses of Allah, reciting the Book of Allah and studying it between them, except that tranquility descends upon them, mercy envelops them, angels surround them, and Allah mentions them to those with Him.',
    topic: 'Dhikr & Dua',
    grade: 'Sahih',
    reflection: 'The sacred tranquility that descends whenever believers pause to recite the Quran and contemplate sacred wisdom.',
  },
  {
    id: 'bukhari_5641',
    book: 'Sahih al-Bukhari',
    hadithNumber: '5641',
    chapter: 'Patience in Illness and Calamities',
    narrator: 'Abu Sa\'id al-Khudri & Abu Hurairah (RA)',
    arabicText: 'مَا يُصِيبُ الْمُسْلِمَ مِنْ نَصَبٍ وَلاَ وَصَبٍ وَلاَ هَمٍّ وَلاَ حُزْنٍ وَلاَ أَذًى وَلاَ غَمٍّ حَتَّى الشَّوْكَةِ يُشَاكُهَا، إِلاَّ كَفَّرَ اللَّهُ بِهَا مِنْ خَطَايَاهُ.',
    englishTranslation: 'No fatigue, illness, worry, sorrow, harm, or grief afflicts a Muslim—even the prick of a thorn—except that Allah expiates some of his sins by means of it.',
    topic: 'Patience & Trials',
    grade: 'Sahih',
    reflection: 'Even silent hardships, anxiety, and mundane exhaustion become a source of divine purification when borne with patient trust.',
  },
  {
    id: 'tirmidhi_2499',
    book: 'Jami` at-Tirmidhi',
    hadithNumber: '2499',
    chapter: 'Forgiveness and Tawbah',
    narrator: 'Anas ibn Malik (RA)',
    arabicText: 'قَالَ اللَّهُ تَبَارَكَ وَتَعَالَى: يَا ابْنَ آدَمَ إِنَّكَ مَا دَعَوْتَنِي وَرَجَوْتَنِي غَفَرْتُ لَكَ عَلَى مَا كَانَ فِيكَ وَلاَ أُبَالِي، يَا ابْنَ آدَمَ لَوْ بَلَغَتْ ذُنُوبُكَ عَنَانَ السَّمَاءِ ثُمَّ اسْتَغْفَرْتَنِي غَفَرْتُ لَكَ...',
    englishTranslation: 'Allah the Almighty declared: "O son of Adam, so long as you call upon Me and ask of Me, I shall forgive you for what you have done, and I shall not mind. O son of Adam, were your sins to reach the clouds of the sky and then you asked forgiveness of Me, I would forgive you."',
    topic: 'Repentance & Mercy',
    grade: 'Sahih',
    reflection: 'The ocean of divine mercy is infinite. Never despair or doubt the readiness of Allah to forgive a genuinely remorseful heart.',
  },
  {
    id: 'nawawi_15',
    book: 'An-Nawawi 40 Hadith',
    hadithNumber: '15',
    chapter: 'Speaking Good or Keeping Silent',
    narrator: 'Abu Hurairah (RA)',
    arabicText: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ، وَمَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ جَارَهُ، وَمَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ ضَيْفَهُ.',
    englishTranslation: 'Whoever believes in Allah and the Last Day should speak good or remain silent. And whoever believes in Allah and the Last Day should be hospitable to his neighbor. And whoever believes in Allah and the Last Day should be generous to his guest.',
    topic: 'Character & Akhlaq',
    grade: 'Sahih',
    reflection: 'Guarding the tongue from harmful gossip, falsehood, and bitterness is a direct reflection of belief in the Hereafter.',
  },
  {
    id: 'muslim_1015',
    book: 'Sahih Muslim',
    hadithNumber: '1015',
    chapter: 'Charity in Every Good Deed',
    narrator: 'Abu Dharr (RA)',
    arabicText: 'إِنَّ بِكُلِّ تَسْبِيحَةٍ صَدَقَةً، وَكُلِّ تَكْبِيرَةٍ صَدَقَةٌ، وَكُلِّ تَحْمِيدَةٍ صَدَقَةٌ، وَكُلِّ تَهْلِيلَةٍ صَدَقَةٌ، وَأَمْرٌ بِالْمَعْرُوفِ صَدَقَةٌ، وَنَهْىٌ عَنْ مُنْكَرٍ صَدَقَةٌ، وَفِي بُضْعِ أَحَدِكُمْ صَدَقَةٌ.',
    englishTranslation: 'In every Tasbeeh (SubhanAllah) is charity, in every Takbeer (Allahu Akbar) is charity, in every Tahmeed (Alhamdulillah) is charity, in every Tahleel (La ilaha illallah) is charity, enjoining good is charity, and forbidding evil is charity.',
    topic: 'Charity & Kindness',
    grade: 'Sahih',
    reflection: 'Charity is not limited to financial wealth. Every mindful praise of Allah and every supportive gesture is recorded as ongoing charity.',
  },
];
