export interface SurahMeta {
  number: number;
  name: string;
  fullNameArabic: string;
  englishName: string;
  englishNameTranslation: string;
  numberOfAyahs: number;
  revelationType: "Meccan" | "Medinan";
  startJuz: number;
  audioUrl: string;
}

export const ALL_114_SURAHS: SurahMeta[] = [
  {
    "number": 1,
    "name": "ٱلْفَاتِحَةِ",
    "fullNameArabic": "سُورَةُ ٱلْفَاتِحَةِ",
    "englishName": "Al-Faatiha",
    "englishNameTranslation": "The Opening",
    "numberOfAyahs": 7,
    "revelationType": "Meccan",
    "startJuz": 1,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/1.mp3"
  },
  {
    "number": 2,
    "name": "البَقَرَةِ",
    "fullNameArabic": "سُورَةُ البَقَرَةِ",
    "englishName": "Al-Baqara",
    "englishNameTranslation": "The Cow",
    "numberOfAyahs": 286,
    "revelationType": "Medinan",
    "startJuz": 1,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/2.mp3"
  },
  {
    "number": 3,
    "name": "آلِ عِمۡرَانَ",
    "fullNameArabic": "سُورَةُ آلِ عِمۡرَانَ",
    "englishName": "Aal-i-Imraan",
    "englishNameTranslation": "The Family of Imraan",
    "numberOfAyahs": 200,
    "revelationType": "Medinan",
    "startJuz": 3,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/3.mp3"
  },
  {
    "number": 4,
    "name": "النِّسَاءِ",
    "fullNameArabic": "سُورَةُ النِّسَاءِ",
    "englishName": "An-Nisaa",
    "englishNameTranslation": "The Women",
    "numberOfAyahs": 176,
    "revelationType": "Medinan",
    "startJuz": 4,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/4.mp3"
  },
  {
    "number": 5,
    "name": "المَائـِدَةِ",
    "fullNameArabic": "سُورَةُ المَائـِدَةِ",
    "englishName": "Al-Maaida",
    "englishNameTranslation": "The Table",
    "numberOfAyahs": 120,
    "revelationType": "Medinan",
    "startJuz": 6,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/5.mp3"
  },
  {
    "number": 6,
    "name": "الأَنۡعَامِ",
    "fullNameArabic": "سُورَةُ الأَنۡعَامِ",
    "englishName": "Al-An'aam",
    "englishNameTranslation": "The Cattle",
    "numberOfAyahs": 165,
    "revelationType": "Meccan",
    "startJuz": 7,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/6.mp3"
  },
  {
    "number": 7,
    "name": "الأَعۡرَافِ",
    "fullNameArabic": "سُورَةُ الأَعۡرَافِ",
    "englishName": "Al-A'raaf",
    "englishNameTranslation": "The Heights",
    "numberOfAyahs": 206,
    "revelationType": "Meccan",
    "startJuz": 8,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/7.mp3"
  },
  {
    "number": 8,
    "name": "الأَنفَالِ",
    "fullNameArabic": "سُورَةُ الأَنفَالِ",
    "englishName": "Al-Anfaal",
    "englishNameTranslation": "The Spoils of War",
    "numberOfAyahs": 75,
    "revelationType": "Medinan",
    "startJuz": 9,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/8.mp3"
  },
  {
    "number": 9,
    "name": "التَّوۡبَةِ",
    "fullNameArabic": "سُورَةُ التَّوۡبَةِ",
    "englishName": "At-Tawba",
    "englishNameTranslation": "The Repentance",
    "numberOfAyahs": 129,
    "revelationType": "Medinan",
    "startJuz": 10,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/9.mp3"
  },
  {
    "number": 10,
    "name": "يُونُسَ",
    "fullNameArabic": "سُورَةُ يُونُسَ",
    "englishName": "Yunus",
    "englishNameTranslation": "Jonas",
    "numberOfAyahs": 109,
    "revelationType": "Meccan",
    "startJuz": 11,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/10.mp3"
  },
  {
    "number": 11,
    "name": "هُودٍ",
    "fullNameArabic": "سُورَةُ هُودٍ",
    "englishName": "Hud",
    "englishNameTranslation": "Hud",
    "numberOfAyahs": 123,
    "revelationType": "Meccan",
    "startJuz": 11,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/11.mp3"
  },
  {
    "number": 12,
    "name": "يُوسُفَ",
    "fullNameArabic": "سُورَةُ يُوسُفَ",
    "englishName": "Yusuf",
    "englishNameTranslation": "Joseph",
    "numberOfAyahs": 111,
    "revelationType": "Meccan",
    "startJuz": 12,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/12.mp3"
  },
  {
    "number": 13,
    "name": "الرَّعۡدِ",
    "fullNameArabic": "سُورَةُ الرَّعۡدِ",
    "englishName": "Ar-Ra'd",
    "englishNameTranslation": "The Thunder",
    "numberOfAyahs": 43,
    "revelationType": "Medinan",
    "startJuz": 13,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/13.mp3"
  },
  {
    "number": 14,
    "name": "إِبۡرَاهِيمَ",
    "fullNameArabic": "سُورَةُ إِبۡرَاهِيمَ",
    "englishName": "Ibrahim",
    "englishNameTranslation": "Abraham",
    "numberOfAyahs": 52,
    "revelationType": "Meccan",
    "startJuz": 13,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/14.mp3"
  },
  {
    "number": 15,
    "name": "الحِجۡرِ",
    "fullNameArabic": "سُورَةُ الحِجۡرِ",
    "englishName": "Al-Hijr",
    "englishNameTranslation": "The Rock",
    "numberOfAyahs": 99,
    "revelationType": "Meccan",
    "startJuz": 14,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/15.mp3"
  },
  {
    "number": 16,
    "name": "النَّحۡلِ",
    "fullNameArabic": "سُورَةُ النَّحۡلِ",
    "englishName": "An-Nahl",
    "englishNameTranslation": "The Bee",
    "numberOfAyahs": 128,
    "revelationType": "Meccan",
    "startJuz": 14,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/16.mp3"
  },
  {
    "number": 17,
    "name": "الإِسۡرَاءِ",
    "fullNameArabic": "سُورَةُ الإِسۡرَاءِ",
    "englishName": "Al-Israa",
    "englishNameTranslation": "The Night Journey",
    "numberOfAyahs": 111,
    "revelationType": "Meccan",
    "startJuz": 15,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/17.mp3"
  },
  {
    "number": 18,
    "name": "الكَهۡفِ",
    "fullNameArabic": "سُورَةُ الكَهۡفِ",
    "englishName": "Al-Kahf",
    "englishNameTranslation": "The Cave",
    "numberOfAyahs": 110,
    "revelationType": "Meccan",
    "startJuz": 15,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/18.mp3"
  },
  {
    "number": 19,
    "name": "مَرۡيَمَ",
    "fullNameArabic": "سُورَةُ مَرۡيَمَ",
    "englishName": "Maryam",
    "englishNameTranslation": "Mary",
    "numberOfAyahs": 98,
    "revelationType": "Meccan",
    "startJuz": 16,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/19.mp3"
  },
  {
    "number": 20,
    "name": "طه",
    "fullNameArabic": "سُورَةُ طه",
    "englishName": "Taa-Haa",
    "englishNameTranslation": "Taa-Haa",
    "numberOfAyahs": 135,
    "revelationType": "Meccan",
    "startJuz": 16,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/20.mp3"
  },
  {
    "number": 21,
    "name": "الأَنبِيَاءِ",
    "fullNameArabic": "سُورَةُ الأَنبِيَاءِ",
    "englishName": "Al-Anbiyaa",
    "englishNameTranslation": "The Prophets",
    "numberOfAyahs": 112,
    "revelationType": "Meccan",
    "startJuz": 17,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/21.mp3"
  },
  {
    "number": 22,
    "name": "الحَجِّ",
    "fullNameArabic": "سُورَةُ الحَجِّ",
    "englishName": "Al-Hajj",
    "englishNameTranslation": "The Pilgrimage",
    "numberOfAyahs": 78,
    "revelationType": "Medinan",
    "startJuz": 17,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/22.mp3"
  },
  {
    "number": 23,
    "name": "المُؤۡمِنُونَ",
    "fullNameArabic": "سُورَةُ المُؤۡمِنُونَ",
    "englishName": "Al-Muminoon",
    "englishNameTranslation": "The Believers",
    "numberOfAyahs": 118,
    "revelationType": "Meccan",
    "startJuz": 18,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/23.mp3"
  },
  {
    "number": 24,
    "name": "النُّورِ",
    "fullNameArabic": "سُورَةُ النُّورِ",
    "englishName": "An-Noor",
    "englishNameTranslation": "The Light",
    "numberOfAyahs": 64,
    "revelationType": "Medinan",
    "startJuz": 18,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/24.mp3"
  },
  {
    "number": 25,
    "name": "الفُرۡقَانِ",
    "fullNameArabic": "سُورَةُ الفُرۡقَانِ",
    "englishName": "Al-Furqaan",
    "englishNameTranslation": "The Criterion",
    "numberOfAyahs": 77,
    "revelationType": "Meccan",
    "startJuz": 18,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/25.mp3"
  },
  {
    "number": 26,
    "name": "الشُّعَرَاءِ",
    "fullNameArabic": "سُورَةُ الشُّعَرَاءِ",
    "englishName": "Ash-Shu'araa",
    "englishNameTranslation": "The Poets",
    "numberOfAyahs": 227,
    "revelationType": "Meccan",
    "startJuz": 19,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/26.mp3"
  },
  {
    "number": 27,
    "name": "النَّمۡلِ",
    "fullNameArabic": "سُورَةُ النَّمۡلِ",
    "englishName": "An-Naml",
    "englishNameTranslation": "The Ant",
    "numberOfAyahs": 93,
    "revelationType": "Meccan",
    "startJuz": 19,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/27.mp3"
  },
  {
    "number": 28,
    "name": "القَصَصِ",
    "fullNameArabic": "سُورَةُ القَصَصِ",
    "englishName": "Al-Qasas",
    "englishNameTranslation": "The Stories",
    "numberOfAyahs": 88,
    "revelationType": "Meccan",
    "startJuz": 20,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/28.mp3"
  },
  {
    "number": 29,
    "name": "العَنكَبُوتِ",
    "fullNameArabic": "سُورَةُ العَنكَبُوتِ",
    "englishName": "Al-Ankaboot",
    "englishNameTranslation": "The Spider",
    "numberOfAyahs": 69,
    "revelationType": "Meccan",
    "startJuz": 20,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/29.mp3"
  },
  {
    "number": 30,
    "name": "الرُّومِ",
    "fullNameArabic": "سُورَةُ الرُّومِ",
    "englishName": "Ar-Room",
    "englishNameTranslation": "The Romans",
    "numberOfAyahs": 60,
    "revelationType": "Meccan",
    "startJuz": 21,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/30.mp3"
  },
  {
    "number": 31,
    "name": "لُقۡمَانَ",
    "fullNameArabic": "سُورَةُ لُقۡمَانَ",
    "englishName": "Luqman",
    "englishNameTranslation": "Luqman",
    "numberOfAyahs": 34,
    "revelationType": "Meccan",
    "startJuz": 21,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/31.mp3"
  },
  {
    "number": 32,
    "name": "السَّجۡدَةِ",
    "fullNameArabic": "سُورَةُ السَّجۡدَةِ",
    "englishName": "As-Sajda",
    "englishNameTranslation": "The Prostration",
    "numberOfAyahs": 30,
    "revelationType": "Meccan",
    "startJuz": 21,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/32.mp3"
  },
  {
    "number": 33,
    "name": "الأَحۡزَابِ",
    "fullNameArabic": "سُورَةُ الأَحۡزَابِ",
    "englishName": "Al-Ahzaab",
    "englishNameTranslation": "The Clans",
    "numberOfAyahs": 73,
    "revelationType": "Medinan",
    "startJuz": 21,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/33.mp3"
  },
  {
    "number": 34,
    "name": "سَبَإٍ",
    "fullNameArabic": "سُورَةُ سَبَإٍ",
    "englishName": "Saba",
    "englishNameTranslation": "Sheba",
    "numberOfAyahs": 54,
    "revelationType": "Meccan",
    "startJuz": 22,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/34.mp3"
  },
  {
    "number": 35,
    "name": "فَاطِرٍ",
    "fullNameArabic": "سُورَةُ فَاطِرٍ",
    "englishName": "Faatir",
    "englishNameTranslation": "The Originator",
    "numberOfAyahs": 45,
    "revelationType": "Meccan",
    "startJuz": 22,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/35.mp3"
  },
  {
    "number": 36,
    "name": "يسٓ",
    "fullNameArabic": "سُورَةُ يسٓ",
    "englishName": "Yaseen",
    "englishNameTranslation": "Yaseen",
    "numberOfAyahs": 83,
    "revelationType": "Meccan",
    "startJuz": 22,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/36.mp3"
  },
  {
    "number": 37,
    "name": "الصَّافَّاتِ",
    "fullNameArabic": "سُورَةُ الصَّافَّاتِ",
    "englishName": "As-Saaffaat",
    "englishNameTranslation": "Those drawn up in Ranks",
    "numberOfAyahs": 182,
    "revelationType": "Meccan",
    "startJuz": 23,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/37.mp3"
  },
  {
    "number": 38,
    "name": "صٓ",
    "fullNameArabic": "سُورَةُ صٓ",
    "englishName": "Saad",
    "englishNameTranslation": "The letter Saad",
    "numberOfAyahs": 88,
    "revelationType": "Meccan",
    "startJuz": 23,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/38.mp3"
  },
  {
    "number": 39,
    "name": "الزُّمَرِ",
    "fullNameArabic": "سُورَةُ الزُّمَرِ",
    "englishName": "Az-Zumar",
    "englishNameTranslation": "The Groups",
    "numberOfAyahs": 75,
    "revelationType": "Meccan",
    "startJuz": 23,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/39.mp3"
  },
  {
    "number": 40,
    "name": "غَافِرٍ",
    "fullNameArabic": "سُورَةُ غَافِرٍ",
    "englishName": "Ghafir",
    "englishNameTranslation": "The Forgiver",
    "numberOfAyahs": 85,
    "revelationType": "Meccan",
    "startJuz": 24,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/40.mp3"
  },
  {
    "number": 41,
    "name": "فُصِّلَتۡ",
    "fullNameArabic": "سُورَةُ فُصِّلَتۡ",
    "englishName": "Fussilat",
    "englishNameTranslation": "Explained in detail",
    "numberOfAyahs": 54,
    "revelationType": "Meccan",
    "startJuz": 24,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/41.mp3"
  },
  {
    "number": 42,
    "name": "الشُّورَىٰ",
    "fullNameArabic": "سُورَةُ الشُّورَىٰ",
    "englishName": "Ash-Shura",
    "englishNameTranslation": "Consultation",
    "numberOfAyahs": 53,
    "revelationType": "Meccan",
    "startJuz": 25,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/42.mp3"
  },
  {
    "number": 43,
    "name": "الزُّخۡرُفِ",
    "fullNameArabic": "سُورَةُ الزُّخۡرُفِ",
    "englishName": "Az-Zukhruf",
    "englishNameTranslation": "Ornaments of gold",
    "numberOfAyahs": 89,
    "revelationType": "Meccan",
    "startJuz": 25,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/43.mp3"
  },
  {
    "number": 44,
    "name": "الدُّخَانِ",
    "fullNameArabic": "سُورَةُ الدُّخَانِ",
    "englishName": "Ad-Dukhaan",
    "englishNameTranslation": "The Smoke",
    "numberOfAyahs": 59,
    "revelationType": "Meccan",
    "startJuz": 25,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/44.mp3"
  },
  {
    "number": 45,
    "name": "الجَاثِيَةِ",
    "fullNameArabic": "سُورَةُ الجَاثِيَةِ",
    "englishName": "Al-Jaathiya",
    "englishNameTranslation": "Crouching",
    "numberOfAyahs": 37,
    "revelationType": "Meccan",
    "startJuz": 25,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/45.mp3"
  },
  {
    "number": 46,
    "name": "الأَحۡقَافِ",
    "fullNameArabic": "سُورَةُ الأَحۡقَافِ",
    "englishName": "Al-Ahqaf",
    "englishNameTranslation": "The Dunes",
    "numberOfAyahs": 35,
    "revelationType": "Meccan",
    "startJuz": 26,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/46.mp3"
  },
  {
    "number": 47,
    "name": "مُحَمَّدٍ",
    "fullNameArabic": "سُورَةُ مُحَمَّدٍ",
    "englishName": "Muhammad",
    "englishNameTranslation": "Muhammad",
    "numberOfAyahs": 38,
    "revelationType": "Medinan",
    "startJuz": 26,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/47.mp3"
  },
  {
    "number": 48,
    "name": "الفَتۡحِ",
    "fullNameArabic": "سُورَةُ الفَتۡحِ",
    "englishName": "Al-Fath",
    "englishNameTranslation": "The Victory",
    "numberOfAyahs": 29,
    "revelationType": "Medinan",
    "startJuz": 26,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/48.mp3"
  },
  {
    "number": 49,
    "name": "الحُجُرَاتِ",
    "fullNameArabic": "سُورَةُ الحُجُرَاتِ",
    "englishName": "Al-Hujuraat",
    "englishNameTranslation": "The Inner Apartments",
    "numberOfAyahs": 18,
    "revelationType": "Medinan",
    "startJuz": 26,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/49.mp3"
  },
  {
    "number": 50,
    "name": "قٓ",
    "fullNameArabic": "سُورَةُ قٓ",
    "englishName": "Qaaf",
    "englishNameTranslation": "The letter Qaaf",
    "numberOfAyahs": 45,
    "revelationType": "Meccan",
    "startJuz": 26,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/50.mp3"
  },
  {
    "number": 51,
    "name": "الذَّارِيَاتِ",
    "fullNameArabic": "سُورَةُ الذَّارِيَاتِ",
    "englishName": "Adh-Dhaariyat",
    "englishNameTranslation": "The Winnowing Winds",
    "numberOfAyahs": 60,
    "revelationType": "Meccan",
    "startJuz": 26,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/51.mp3"
  },
  {
    "number": 52,
    "name": "الطُّورِ",
    "fullNameArabic": "سُورَةُ الطُّورِ",
    "englishName": "At-Tur",
    "englishNameTranslation": "The Mount",
    "numberOfAyahs": 49,
    "revelationType": "Meccan",
    "startJuz": 27,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/52.mp3"
  },
  {
    "number": 53,
    "name": "النَّجۡمِ",
    "fullNameArabic": "سُورَةُ النَّجۡمِ",
    "englishName": "An-Najm",
    "englishNameTranslation": "The Star",
    "numberOfAyahs": 62,
    "revelationType": "Meccan",
    "startJuz": 27,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/53.mp3"
  },
  {
    "number": 54,
    "name": "القَمَرِ",
    "fullNameArabic": "سُورَةُ القَمَرِ",
    "englishName": "Al-Qamar",
    "englishNameTranslation": "The Moon",
    "numberOfAyahs": 55,
    "revelationType": "Meccan",
    "startJuz": 27,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/54.mp3"
  },
  {
    "number": 55,
    "name": "الرَّحۡمَٰن",
    "fullNameArabic": "سُورَةُ الرَّحۡمَٰن",
    "englishName": "Ar-Rahmaan",
    "englishNameTranslation": "The Beneficent",
    "numberOfAyahs": 78,
    "revelationType": "Medinan",
    "startJuz": 27,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/55.mp3"
  },
  {
    "number": 56,
    "name": "الوَاقِعَةِ",
    "fullNameArabic": "سُورَةُ الوَاقِعَةِ",
    "englishName": "Al-Waaqia",
    "englishNameTranslation": "The Inevitable",
    "numberOfAyahs": 96,
    "revelationType": "Meccan",
    "startJuz": 27,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/56.mp3"
  },
  {
    "number": 57,
    "name": "الحَدِيدِ",
    "fullNameArabic": "سُورَةُ الحَدِيدِ",
    "englishName": "Al-Hadid",
    "englishNameTranslation": "The Iron",
    "numberOfAyahs": 29,
    "revelationType": "Medinan",
    "startJuz": 27,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/57.mp3"
  },
  {
    "number": 58,
    "name": "المُجَادلَةِ",
    "fullNameArabic": "سُورَةُ المُجَادلَةِ",
    "englishName": "Al-Mujaadila",
    "englishNameTranslation": "The Pleading Woman",
    "numberOfAyahs": 22,
    "revelationType": "Medinan",
    "startJuz": 28,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/58.mp3"
  },
  {
    "number": 59,
    "name": "الحَشۡرِ",
    "fullNameArabic": "سُورَةُ الحَشۡرِ",
    "englishName": "Al-Hashr",
    "englishNameTranslation": "The Exile",
    "numberOfAyahs": 24,
    "revelationType": "Medinan",
    "startJuz": 28,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/59.mp3"
  },
  {
    "number": 60,
    "name": "المُمۡتَحنَةِ",
    "fullNameArabic": "سُورَةُ المُمۡتَحنَةِ",
    "englishName": "Al-Mumtahana",
    "englishNameTranslation": "She that is to be examined",
    "numberOfAyahs": 13,
    "revelationType": "Medinan",
    "startJuz": 28,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/60.mp3"
  },
  {
    "number": 61,
    "name": "الصَّفِّ",
    "fullNameArabic": "سُورَةُ الصَّفِّ",
    "englishName": "As-Saff",
    "englishNameTranslation": "The Ranks",
    "numberOfAyahs": 14,
    "revelationType": "Medinan",
    "startJuz": 28,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/61.mp3"
  },
  {
    "number": 62,
    "name": "الجُمُعَةِ",
    "fullNameArabic": "سُورَةُ الجُمُعَةِ",
    "englishName": "Al-Jumu'a",
    "englishNameTranslation": "Friday",
    "numberOfAyahs": 11,
    "revelationType": "Medinan",
    "startJuz": 28,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/62.mp3"
  },
  {
    "number": 63,
    "name": "المُنَافِقُونَ",
    "fullNameArabic": "سُورَةُ المُنَافِقُونَ",
    "englishName": "Al-Munaafiqoon",
    "englishNameTranslation": "The Hypocrites",
    "numberOfAyahs": 11,
    "revelationType": "Medinan",
    "startJuz": 28,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/63.mp3"
  },
  {
    "number": 64,
    "name": "التَّغَابُنِ",
    "fullNameArabic": "سُورَةُ التَّغَابُنِ",
    "englishName": "At-Taghaabun",
    "englishNameTranslation": "Mutual Disillusion",
    "numberOfAyahs": 18,
    "revelationType": "Medinan",
    "startJuz": 28,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/64.mp3"
  },
  {
    "number": 65,
    "name": "الطَّلَاقِ",
    "fullNameArabic": "سُورَةُ الطَّلَاقِ",
    "englishName": "At-Talaaq",
    "englishNameTranslation": "Divorce",
    "numberOfAyahs": 12,
    "revelationType": "Medinan",
    "startJuz": 28,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/65.mp3"
  },
  {
    "number": 66,
    "name": "التَّحۡرِيمِ",
    "fullNameArabic": "سُورَةُ التَّحۡرِيمِ",
    "englishName": "At-Tahrim",
    "englishNameTranslation": "The Prohibition",
    "numberOfAyahs": 12,
    "revelationType": "Medinan",
    "startJuz": 28,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/66.mp3"
  },
  {
    "number": 67,
    "name": "المُلۡكِ",
    "fullNameArabic": "سُورَةُ المُلۡكِ",
    "englishName": "Al-Mulk",
    "englishNameTranslation": "The Sovereignty",
    "numberOfAyahs": 30,
    "revelationType": "Meccan",
    "startJuz": 29,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/67.mp3"
  },
  {
    "number": 68,
    "name": "القَلَمِ",
    "fullNameArabic": "سُورَةُ القَلَمِ",
    "englishName": "Al-Qalam",
    "englishNameTranslation": "The Pen",
    "numberOfAyahs": 52,
    "revelationType": "Meccan",
    "startJuz": 29,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/68.mp3"
  },
  {
    "number": 69,
    "name": "الحَاقَّةِ",
    "fullNameArabic": "سُورَةُ الحَاقَّةِ",
    "englishName": "Al-Haaqqa",
    "englishNameTranslation": "The Reality",
    "numberOfAyahs": 52,
    "revelationType": "Meccan",
    "startJuz": 29,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/69.mp3"
  },
  {
    "number": 70,
    "name": "المَعَارِجِ",
    "fullNameArabic": "سُورَةُ المَعَارِجِ",
    "englishName": "Al-Ma'aarij",
    "englishNameTranslation": "The Ascending Stairways",
    "numberOfAyahs": 44,
    "revelationType": "Meccan",
    "startJuz": 29,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/70.mp3"
  },
  {
    "number": 71,
    "name": "نُوحٍ",
    "fullNameArabic": "سُورَةُ نُوحٍ",
    "englishName": "Nooh",
    "englishNameTranslation": "Noah",
    "numberOfAyahs": 28,
    "revelationType": "Meccan",
    "startJuz": 29,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/71.mp3"
  },
  {
    "number": 72,
    "name": "الجِنِّ",
    "fullNameArabic": "سُورَةُ الجِنِّ",
    "englishName": "Al-Jinn",
    "englishNameTranslation": "The Jinn",
    "numberOfAyahs": 28,
    "revelationType": "Meccan",
    "startJuz": 29,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/72.mp3"
  },
  {
    "number": 73,
    "name": "المُزَّمِّلِ",
    "fullNameArabic": "سُورَةُ المُزَّمِّلِ",
    "englishName": "Al-Muzzammil",
    "englishNameTranslation": "The Enshrouded One",
    "numberOfAyahs": 20,
    "revelationType": "Meccan",
    "startJuz": 29,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/73.mp3"
  },
  {
    "number": 74,
    "name": "المُدَّثِّرِ",
    "fullNameArabic": "سُورَةُ المُدَّثِّرِ",
    "englishName": "Al-Muddaththir",
    "englishNameTranslation": "The Cloaked One",
    "numberOfAyahs": 56,
    "revelationType": "Meccan",
    "startJuz": 29,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/74.mp3"
  },
  {
    "number": 75,
    "name": "القِيَامَةِ",
    "fullNameArabic": "سُورَةُ القِيَامَةِ",
    "englishName": "Al-Qiyaama",
    "englishNameTranslation": "The Resurrection",
    "numberOfAyahs": 40,
    "revelationType": "Meccan",
    "startJuz": 29,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/75.mp3"
  },
  {
    "number": 76,
    "name": "الإِنسَانِ",
    "fullNameArabic": "سُورَةُ الإِنسَانِ",
    "englishName": "Al-Insaan",
    "englishNameTranslation": "Man",
    "numberOfAyahs": 31,
    "revelationType": "Medinan",
    "startJuz": 29,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/76.mp3"
  },
  {
    "number": 77,
    "name": "المُرۡسَلَاتِ",
    "fullNameArabic": "سُورَةُ المُرۡسَلَاتِ",
    "englishName": "Al-Mursalaat",
    "englishNameTranslation": "The Emissaries",
    "numberOfAyahs": 50,
    "revelationType": "Meccan",
    "startJuz": 29,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/77.mp3"
  },
  {
    "number": 78,
    "name": "النَّبَإِ",
    "fullNameArabic": "سُورَةُ النَّبَإِ",
    "englishName": "An-Naba",
    "englishNameTranslation": "The Announcement",
    "numberOfAyahs": 40,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/78.mp3"
  },
  {
    "number": 79,
    "name": "النَّازِعَاتِ",
    "fullNameArabic": "سُورَةُ النَّازِعَاتِ",
    "englishName": "An-Naazi'aat",
    "englishNameTranslation": "Those who drag forth",
    "numberOfAyahs": 46,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/79.mp3"
  },
  {
    "number": 80,
    "name": "عَبَسَ",
    "fullNameArabic": "سُورَةُ عَبَسَ",
    "englishName": "Abasa",
    "englishNameTranslation": "He frowned",
    "numberOfAyahs": 42,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/80.mp3"
  },
  {
    "number": 81,
    "name": "التَّكۡوِيرِ",
    "fullNameArabic": "سُورَةُ التَّكۡوِيرِ",
    "englishName": "At-Takwir",
    "englishNameTranslation": "The Overthrowing",
    "numberOfAyahs": 29,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/81.mp3"
  },
  {
    "number": 82,
    "name": "الانفِطَارِ",
    "fullNameArabic": "سُورَةُ الانفِطَارِ",
    "englishName": "Al-Infitaar",
    "englishNameTranslation": "The Cleaving",
    "numberOfAyahs": 19,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/82.mp3"
  },
  {
    "number": 83,
    "name": "المُطَفِّفِينَ",
    "fullNameArabic": "سُورَةُ المُطَفِّفِينَ",
    "englishName": "Al-Mutaffifin",
    "englishNameTranslation": "Defrauding",
    "numberOfAyahs": 36,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/83.mp3"
  },
  {
    "number": 84,
    "name": "الانشِقَاقِ",
    "fullNameArabic": "سُورَةُ الانشِقَاقِ",
    "englishName": "Al-Inshiqaaq",
    "englishNameTranslation": "The Splitting Open",
    "numberOfAyahs": 25,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/84.mp3"
  },
  {
    "number": 85,
    "name": "البُرُوجِ",
    "fullNameArabic": "سُورَةُ البُرُوجِ",
    "englishName": "Al-Burooj",
    "englishNameTranslation": "The Constellations",
    "numberOfAyahs": 22,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/85.mp3"
  },
  {
    "number": 86,
    "name": "الطَّارِقِ",
    "fullNameArabic": "سُورَةُ الطَّارِقِ",
    "englishName": "At-Taariq",
    "englishNameTranslation": "The Morning Star",
    "numberOfAyahs": 17,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/86.mp3"
  },
  {
    "number": 87,
    "name": "الأَعۡلَىٰ",
    "fullNameArabic": "سُورَةُ الأَعۡلَىٰ",
    "englishName": "Al-A'laa",
    "englishNameTranslation": "The Most High",
    "numberOfAyahs": 19,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/87.mp3"
  },
  {
    "number": 88,
    "name": "الغَاشِيَةِ",
    "fullNameArabic": "سُورَةُ الغَاشِيَةِ",
    "englishName": "Al-Ghaashiya",
    "englishNameTranslation": "The Overwhelming",
    "numberOfAyahs": 26,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/88.mp3"
  },
  {
    "number": 89,
    "name": "الفَجۡرِ",
    "fullNameArabic": "سُورَةُ الفَجۡرِ",
    "englishName": "Al-Fajr",
    "englishNameTranslation": "The Dawn",
    "numberOfAyahs": 30,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/89.mp3"
  },
  {
    "number": 90,
    "name": "البَلَدِ",
    "fullNameArabic": "سُورَةُ البَلَدِ",
    "englishName": "Al-Balad",
    "englishNameTranslation": "The City",
    "numberOfAyahs": 20,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/90.mp3"
  },
  {
    "number": 91,
    "name": "الشَّمۡسِ",
    "fullNameArabic": "سُورَةُ الشَّمۡسِ",
    "englishName": "Ash-Shams",
    "englishNameTranslation": "The Sun",
    "numberOfAyahs": 15,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/91.mp3"
  },
  {
    "number": 92,
    "name": "اللَّيۡلِ",
    "fullNameArabic": "سُورَةُ اللَّيۡلِ",
    "englishName": "Al-Lail",
    "englishNameTranslation": "The Night",
    "numberOfAyahs": 21,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/92.mp3"
  },
  {
    "number": 93,
    "name": "الضُّحَىٰ",
    "fullNameArabic": "سُورَةُ الضُّحَىٰ",
    "englishName": "Ad-Dhuhaa",
    "englishNameTranslation": "The Morning Hours",
    "numberOfAyahs": 11,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/93.mp3"
  },
  {
    "number": 94,
    "name": "الشَّرۡحِ",
    "fullNameArabic": "سُورَةُ الشَّرۡحِ",
    "englishName": "Ash-Sharh",
    "englishNameTranslation": "The Consolation",
    "numberOfAyahs": 8,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/94.mp3"
  },
  {
    "number": 95,
    "name": "التِّينِ",
    "fullNameArabic": "سُورَةُ التِّينِ",
    "englishName": "At-Tin",
    "englishNameTranslation": "The Fig",
    "numberOfAyahs": 8,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/95.mp3"
  },
  {
    "number": 96,
    "name": "العَلَقِ",
    "fullNameArabic": "سُورَةُ العَلَقِ",
    "englishName": "Al-Alaq",
    "englishNameTranslation": "The Clot",
    "numberOfAyahs": 19,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/96.mp3"
  },
  {
    "number": 97,
    "name": "القَدۡرِ",
    "fullNameArabic": "سُورَةُ القَدۡرِ",
    "englishName": "Al-Qadr",
    "englishNameTranslation": "The Power, Fate",
    "numberOfAyahs": 5,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/97.mp3"
  },
  {
    "number": 98,
    "name": "البَيِّنَةِ",
    "fullNameArabic": "سُورَةُ البَيِّنَةِ",
    "englishName": "Al-Bayyina",
    "englishNameTranslation": "The Evidence",
    "numberOfAyahs": 8,
    "revelationType": "Medinan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/98.mp3"
  },
  {
    "number": 99,
    "name": "الزَّلۡزَلَةِ",
    "fullNameArabic": "سُورَةُ الزَّلۡزَلَةِ",
    "englishName": "Az-Zalzala",
    "englishNameTranslation": "The Earthquake",
    "numberOfAyahs": 8,
    "revelationType": "Medinan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/99.mp3"
  },
  {
    "number": 100,
    "name": "العَادِيَاتِ",
    "fullNameArabic": "سُورَةُ العَادِيَاتِ",
    "englishName": "Al-Aadiyaat",
    "englishNameTranslation": "The Chargers",
    "numberOfAyahs": 11,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/100.mp3"
  },
  {
    "number": 101,
    "name": "القَارِعَةِ",
    "fullNameArabic": "سُورَةُ القَارِعَةِ",
    "englishName": "Al-Qaari'a",
    "englishNameTranslation": "The Calamity",
    "numberOfAyahs": 11,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/101.mp3"
  },
  {
    "number": 102,
    "name": "التَّكَاثُرِ",
    "fullNameArabic": "سُورَةُ التَّكَاثُرِ",
    "englishName": "At-Takaathur",
    "englishNameTranslation": "Competition",
    "numberOfAyahs": 8,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/102.mp3"
  },
  {
    "number": 103,
    "name": "العَصۡرِ",
    "fullNameArabic": "سُورَةُ العَصۡرِ",
    "englishName": "Al-Asr",
    "englishNameTranslation": "The Declining Day, Epoch",
    "numberOfAyahs": 3,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/103.mp3"
  },
  {
    "number": 104,
    "name": "الهُمَزَةِ",
    "fullNameArabic": "سُورَةُ الهُمَزَةِ",
    "englishName": "Al-Humaza",
    "englishNameTranslation": "The Traducer",
    "numberOfAyahs": 9,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/104.mp3"
  },
  {
    "number": 105,
    "name": "الفِيلِ",
    "fullNameArabic": "سُورَةُ الفِيلِ",
    "englishName": "Al-Fil",
    "englishNameTranslation": "The Elephant",
    "numberOfAyahs": 5,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/105.mp3"
  },
  {
    "number": 106,
    "name": "قُرَيۡشٍ",
    "fullNameArabic": "سُورَةُ قُرَيۡشٍ",
    "englishName": "Quraish",
    "englishNameTranslation": "Quraysh",
    "numberOfAyahs": 4,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/106.mp3"
  },
  {
    "number": 107,
    "name": "المَاعُونِ",
    "fullNameArabic": "سُورَةُ المَاعُونِ",
    "englishName": "Al-Maa'un",
    "englishNameTranslation": "Almsgiving",
    "numberOfAyahs": 7,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/107.mp3"
  },
  {
    "number": 108,
    "name": "الكَوۡثَرِ",
    "fullNameArabic": "سُورَةُ الكَوۡثَرِ",
    "englishName": "Al-Kawthar",
    "englishNameTranslation": "Abundance",
    "numberOfAyahs": 3,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/108.mp3"
  },
  {
    "number": 109,
    "name": "الكَافِرُونَ",
    "fullNameArabic": "سُورَةُ الكَافِرُونَ",
    "englishName": "Al-Kaafiroon",
    "englishNameTranslation": "The Disbelievers",
    "numberOfAyahs": 6,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/109.mp3"
  },
  {
    "number": 110,
    "name": "النَّصۡرِ",
    "fullNameArabic": "سُورَةُ النَّصۡرِ",
    "englishName": "An-Nasr",
    "englishNameTranslation": "Divine Support",
    "numberOfAyahs": 3,
    "revelationType": "Medinan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/110.mp3"
  },
  {
    "number": 111,
    "name": "المَسَدِ",
    "fullNameArabic": "سُورَةُ المَسَدِ",
    "englishName": "Al-Masad",
    "englishNameTranslation": "The Palm Fibre",
    "numberOfAyahs": 5,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/111.mp3"
  },
  {
    "number": 112,
    "name": "الإِخۡلَاصِ",
    "fullNameArabic": "سُورَةُ الإِخۡلَاصِ",
    "englishName": "Al-Ikhlaas",
    "englishNameTranslation": "Sincerity",
    "numberOfAyahs": 4,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/112.mp3"
  },
  {
    "number": 113,
    "name": "الفَلَقِ",
    "fullNameArabic": "سُورَةُ الفَلَقِ",
    "englishName": "Al-Falaq",
    "englishNameTranslation": "The Dawn",
    "numberOfAyahs": 5,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/113.mp3"
  },
  {
    "number": 114,
    "name": "النَّاسِ",
    "fullNameArabic": "سُورَةُ النَّاسِ",
    "englishName": "An-Naas",
    "englishNameTranslation": "Mankind",
    "numberOfAyahs": 6,
    "revelationType": "Meccan",
    "startJuz": 30,
    "audioUrl": "https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/114.mp3"
  }
];
