import { ALL_114_SURAHS, SurahMeta } from './quran114List';
import { QuranAyah, QuranSurahDetail, fetchSurah, getCachedSurah } from './quranService';

export type { QuranAyah, QuranSurahDetail, SurahMeta };

export interface QuranSurah {
  number: number;
  name: string;
  englishName: string;
  englishNameTranslation: string;
  numberOfAyahs: number;
  revelationType: 'Meccan' | 'Medinan';
  audioUrl?: string;
  ayahs: QuranAyah[];
}

export { ALL_114_SURAHS, fetchSurah, getCachedSurah };

// Pre-embedded fallback datasets for instant offline reading
export const OFFLINE_FALLBACK_SURAHS: Record<number, QuranAyah[]> = {
  // Surah 1: Al-Fatihah (Complete 7 Ayahs)
  1: [
    {
      number: 1,
      globalNumber: 1,
      arabic: 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ',
      transliteration: 'Bismillāhir-Raḥmānir-Raḥīm',
      translation: 'In the name of Allah, the Entirely Merciful, the Especially Merciful.',
      juz: 1,
      page: 1,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/1.mp3',
    },
    {
      number: 2,
      globalNumber: 2,
      arabic: 'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ',
      transliteration: 'Al-ḥamdu lillāhi Rabbil-\'ālamīn',
      translation: '[All] praise is [due] to Allah, Lord of the worlds -',
      juz: 1,
      page: 1,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/2.mp3',
    },
    {
      number: 3,
      globalNumber: 3,
      arabic: 'ٱلرَّحْمَٰنِ ٱلرَّحِيمِ',
      transliteration: 'Ar-Raḥmānir-Raḥīm',
      translation: 'The Entirely Merciful, the Especially Merciful,',
      juz: 1,
      page: 1,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/3.mp3',
    },
    {
      number: 4,
      globalNumber: 4,
      arabic: 'مَٰلِكِ يَوْمِ ٱلدِّينِ',
      transliteration: 'Māliki yawmid-dīn',
      translation: 'Sovereign of the Day of Recompense.',
      juz: 1,
      page: 1,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/4.mp3',
    },
    {
      number: 5,
      globalNumber: 5,
      arabic: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
      transliteration: 'Iyyāka na\'budu wa iyyāka nasta\'īn',
      translation: 'It is You we worship and You we ask for help.',
      juz: 1,
      page: 1,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/5.mp3',
    },
    {
      number: 6,
      globalNumber: 6,
      arabic: 'ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ',
      transliteration: 'Ihdinaṣ-ṣirāṭal-mustaqīm',
      translation: 'Guide us to the straight path -',
      juz: 1,
      page: 1,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6.mp3',
    },
    {
      number: 7,
      globalNumber: 7,
      arabic: 'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
      transliteration: 'Ṣirāṭal-ladhīna an\'amta \'alayhim ghayril-maghḍūbi \'alayhim wa laḍ-ḍāllīn',
      translation: 'The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.',
      juz: 1,
      page: 1,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/7.mp3',
    },
  ],

  // Surah 108: Al-Kawthar (Complete 3 Ayahs)
  108: [
    {
      number: 1,
      globalNumber: 6194,
      arabic: 'إِنَّآ أَعْطَيْنَٰكَ ٱلْكَوْثَرَ',
      transliteration: 'Innā a\'ṭaynākal-kawthar',
      translation: 'Indeed, We have granted you, [O Muhammad], al-Kawthar (abundant good).',
      juz: 30,
      page: 602,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6194.mp3',
    },
    {
      number: 2,
      globalNumber: 6195,
      arabic: 'فَصَلِّ لِرَبِّكَ وَٱنْحَرْ',
      transliteration: 'Faṣalli li-Rabbika wanḥar',
      translation: 'So pray to your Lord and sacrifice [to Him alone].',
      juz: 30,
      page: 602,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6195.mp3',
    },
    {
      number: 3,
      globalNumber: 6196,
      arabic: 'إِنَّ شَانِئَكَ هُوَ ٱلْأَبْتَرُ',
      transliteration: 'Inna shāni\'aka huwal-abtar',
      translation: 'Indeed, your enemy is the one cut off.',
      juz: 30,
      page: 602,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6196.mp3',
    },
  ],

  // Surah 112: Al-Ikhlas (Complete 4 Ayahs)
  112: [
    {
      number: 1,
      globalNumber: 6222,
      arabic: 'قُلْ هُوَ ٱللَّهُ أَحَدٌ',
      transliteration: 'Qul Huwallāhu Aḥad',
      translation: 'Say, "He is Allah, [who is] One,',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6222.mp3',
    },
    {
      number: 2,
      globalNumber: 6223,
      arabic: 'ٱللَّهُ ٱلصَّمَدُ',
      transliteration: 'Allāhuṣ-Ṣamad',
      translation: 'Allah, the Eternal Refuge.',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6223.mp3',
    },
    {
      number: 3,
      globalNumber: 6224,
      arabic: 'لَمْ يَلِدْ وَلَمْ يُولَدْ',
      transliteration: 'Lam yalid wa lam yūlad',
      translation: 'He neither begets nor is born,',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6224.mp3',
    },
    {
      number: 4,
      globalNumber: 6225,
      arabic: 'وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ',
      transliteration: 'Wa lam yakul-lahū kufuwan aḥad',
      translation: 'Nor is there to Him any equivalent."',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6225.mp3',
    },
  ],

  // Surah 113: Al-Falaq (Complete 5 Ayahs)
  113: [
    {
      number: 1,
      globalNumber: 6226,
      arabic: 'قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ',
      transliteration: 'Qul a\'ūdhu bi-Rabbil-falaq',
      translation: 'Say, "I seek refuge in the Lord of daybreak',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6226.mp3',
    },
    {
      number: 2,
      globalNumber: 6227,
      arabic: 'مِن شَرِّ مَا خَلَقَ',
      transliteration: 'Min sharri mā khalaq',
      translation: 'From the evil of that which He created',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6227.mp3',
    },
    {
      number: 3,
      globalNumber: 6228,
      arabic: 'وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ',
      transliteration: 'Wa min sharri ghāsiqin idhā waqab',
      translation: 'And from the evil of darkness when it settles',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6228.mp3',
    },
    {
      number: 4,
      globalNumber: 6229,
      arabic: 'وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ',
      transliteration: 'Wa min sharrin-naffāthāti fil-\'uqad',
      translation: 'And from the evil of the blowers in knots',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6229.mp3',
    },
    {
      number: 5,
      globalNumber: 6230,
      arabic: 'وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
      transliteration: 'Wa min sharri ḥāsidin idhā ḥasad',
      translation: 'And from the evil of an envier when he envies."',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6230.mp3',
    },
  ],

  // Surah 114: An-Nas (Complete 6 Ayahs)
  114: [
    {
      number: 1,
      globalNumber: 6231,
      arabic: 'قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ',
      transliteration: 'Qul a\'ūdhu bi-Rabbin-nās',
      translation: 'Say, "I seek refuge in the Lord of mankind,',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6231.mp3',
    },
    {
      number: 2,
      globalNumber: 6232,
      arabic: 'مَلِكِ ٱلنَّاسِ',
      transliteration: 'Malikin-nās',
      translation: 'The Sovereign of mankind,',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6232.mp3',
    },
    {
      number: 3,
      globalNumber: 6233,
      arabic: 'إِلَٰهِ ٱلنَّاسِ',
      transliteration: 'Ilāhin-nās',
      translation: 'The God of mankind,',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6233.mp3',
    },
    {
      number: 4,
      globalNumber: 6234,
      arabic: 'مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ',
      transliteration: 'Min sharril-waswāsil-khannās',
      translation: 'From the evil of the retreating whisperer -',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6234.mp3',
    },
    {
      number: 5,
      globalNumber: 6235,
      arabic: 'ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ',
      transliteration: 'Alladhī yuwaswisu fī ṣudūrin-nās',
      translation: 'Who whispers [evil] into the breasts of mankind -',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6235.mp3',
    },
    {
      number: 6,
      globalNumber: 6236,
      arabic: 'مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ',
      transliteration: 'Minal-jinnati wan-nās',
      translation: 'From among the jinn and mankind."',
      juz: 30,
      page: 604,
      sajda: false,
      audioUrl: 'https://cdn.islamic.network/quran/audio/128/ar.alafasy/6236.mp3',
    },
  ],
};

// Legacy array maintained for backward compatibility
export const QURAN_SURAHS: QuranSurah[] = ALL_114_SURAHS.slice(0, 10).map((meta) => ({
  number: meta.number,
  name: meta.name,
  englishName: meta.englishName,
  englishNameTranslation: meta.englishNameTranslation,
  numberOfAyahs: meta.numberOfAyahs,
  revelationType: meta.revelationType,
  audioUrl: meta.audioUrl,
  ayahs: OFFLINE_FALLBACK_SURAHS[meta.number] || [],
}));
